### PR TITLE
Made some Changes 

### PR DESCRIPTION
**Pull request by nimma0001**
Added Filter out the bots
Added Filter out already Added Members
Added new file which automatically get called to compare json
Fixed add_st.py
Many others

### CODE REVIEW

**Comment by imehsanhz** [comment]
Hello.
I need your help.

I am working fine until step 4, but when I run the add_member.py file I get an error.
Both my accounts are members of the group.
What is the problem?


Error : 

Total account: 2
+98********** login success
+98********** login success
This account with phone +98********** is not in target group
This account with phone +98********** is not in target group
From index: 0
Traceback (most recent call last):
  File "D:\add member\south1907\add_member.py", line 156, in <module>
    total_user = filter_clients[0]['users'].__len__()
IndexError: list index out of range

**Comment by imehsanhz** [comment]
I change line 38 in add_member.py
if (group_id == int(group['group_id'])):   >>>>>>        if (group_id == group['group_id']):
and fix this error : This account with phone +98********** is not in target group
but not work.

output is : 
Total account: 2
+98**********  login success
+98**********  login success
From index: 2
disconnect
exiting program wait For4 Some Seconds
total: 0
total time: 0:00:05.140677

**Comment by imehsanhz** [comment]
print("after line 155 ",filter_clients)

[{'phone': '+98**********', 'client': <telethon.client.telegramclient.TelegramClient object at 0x000001F99D50E290>, 'target_group_entity': <telethon.tl.types.InputPeerChannel object at 0x000001F99F36EF20>, 'users': []}, {'phone': '+98**********', 'client': <telethon.client.telegramclient.TelegramClient object at 0x000001F99F36DC60>, 'target_group_entity': <telethon.tl.types.InputPeerChannel object at 0x000001F99F36EBF0>, 'users': []}]

**Comment by nimma0001** [comment]
@imehsanhz hsanhz Join telegram https://t.me/amtcommunity

**Comment by nimma0001** [comment]
And do python get_data.py

**Comment by nimma0001** [comment]
Then do python add_member.py

**Comment by nimma0001** [comment]
@imehsanhz open config.json and remove " " from target id 
Or use this branch 
https://github.com/nimma0001/addmember-telegram/

**Pull request merged**
