### PR TITLE
Updated the code to work with latest Telegram updates

### PR DESCRIPTION
**Pull request by DanielTheGeek**
Unhandled errors were causing the program to shutdown when trying to get data and also add members to groups.

These have been fixed in this update and the program runs smoothly now.

### CODE REVIEW

**Comment by onebyoneby** [comment]
where is  group_target and source   on where

**Comment by DanielTheGeek** [comment]
Rename config.example.json to config.json and put in the right values.

**Review by south1907 — APPROVED** [review]
Thank to DanielTheGeek

**Comment by andreitek** [comment]
Getting this erros also if i open add_member.py on vscode show that have 6 problem in code, but if i dont open add_member.py it says nothing

Traceback (most recent call last):
  File "C:\Users\andre\Desktop\ss\addmember-telegram-master\add_member.py", line 107, in <module>
    total_user = filter_clients[0]['users'].__len__()
IndexError: list index out of range

**Comment by Shanaka0225** [comment]
@south1907 Please can you fix errors for 2023 kindly.....   because this is the best tool for me honestly.. please

**Comment by JulesSkiz** [comment]
Hi, thank you for your work. I am contacting you because I have an error that I can't solve : 

File "/Users/julesskiz/Desktop/addmember-telegram-master/add_member.py", line 148, in <module>
    client(InviteToChannelRequest(target_group_entity, [user_to_add]))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/telethon/client/users.py", line 83, in _call
    result = await future
             ^^^^^^^^^^^^
telethon.errors.rpcerrorlist.PeerFloodError: Too many requests (caused by InviteToChannelRequest)
remove client: +336???????
remain client: 0
END: accounts is empty
disconnect
total: 1
total time: 0:02:00.654563

**Comment by ekinsipahi** [comment]
is this project still working?

**Review by arezgow — COMMENTED** [review]
hello, everytime i login with a new number, after 10 min the number get banned for ever from telegram

**Pull request merged**
